### ISSUE TITLE
GPIO isr service already installed

### ISSUE THREAD

**Issue by AlSimons** [lemariva/uPyCam#18]
Using esptool.py, I erased the flash successfully from my ESP32-CAM, and then flashed this version of the enhanced microPython:
https://raw.githubusercontent.com/lemariva/micropython-camera-driver/master/firmware/micropython_camera_feeeb5ea3_esp32_idf4_4.bin

I cloned uPyCam, and am using this commit a2f62ec9993ed9c7ef76495491da8e28dd118dbd

Moved all the py files onto the ESP32-CAM board using ampy. 

I get this error below after connecting to the network (last output before the error is the network config), and am then dumped back into the repl. The error is:

      E (4780) gpio: gpio_install_isr_service(449): GPIO isr service already installed

Thanks for any insights.
-Al

**Comment by AlSimons** [comment]
Re-erased, flashed, and loaded uPyCam code.  No change.

**Comment by lemariva** [comment]
Hi there, the issue is not related with the application, and it's discussed [here](https://github.com/lemariva/micropython-camera-driver/issues/8). It should not be a problem; the error and the warning do not stop the camera from working. Just ignore it. Otherwise, open [that issue](https://github.com/lemariva/micropython-camera-driver/issues/) again.
